on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: premium3.web-hosting.com
          username: kodedjackson@paygoapi.startershouse.com
          password: ${{ secrets.ftp_password }}
          server-dir: /home/vibrxxrt/paygoapi.startershouse.com/kodedjackson
